### ISSUE TITLE
Events Calendar should not display past events

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#309]
On the `/Events` page, the client does not want past events to be displayed. The database query needs to be updated. Add a WHERE clause to only pull events for the current day and in the future. Looks like the data is being pulled in `CalendarEventDB.GetAllEvents(ApplicationDbContext, bool)`

**Comment by Azael-Hue** [comment]
After testing the most recent version of the repo, I found out this issue was fixed in the commit `130c1c9`, After Cameron addressed the `issue`#317 while implementing the calendar and updating the dates property.
I did some testing with some placeholder/test events on my end and changing the dates on the events and on my system, once done, the events prior to the date in the system would not be displayed.
@JoeProgrammer88

**Comment by JoeProgrammer88** [comment]
@Azael-Hue thanks for confirming this. Since this is complete we can close this issue
